# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Craft-Device standalone executable."""

import os

block_cipher = None

a = Analysis(
    ["run.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("backend/app", "backend/app"),
        ("frontend/dist", "frontend/dist"),
    ],
    hiddenimports=[
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.http.httptools_impl",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.protocols.websockets.wsproto_impl",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        "app",
        "app.main",
        "app.config",
        "app.database",
        "app.models",
        "app.models.user",
        "app.models.tender",
        "app.models.portfolio",
        "app.models.category",
        "app.schemas",
        "app.schemas.user",
        "app.schemas.tender",
        "app.schemas.portfolio",
        "app.routers",
        "app.routers.auth",
        "app.routers.tenders",
        "app.routers.portfolio",
        "app.routers.categories",
        "app.routers.upload",
        "app.routers.stats",
        "app.services",
        "app.services.auth",
        "app.seed",
        "passlib.handlers.bcrypt",
        "bcrypt",
        "jose",
        "multipart",
        "email_validator",
        "aiofiles",
        "sqlalchemy.dialects.sqlite",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="craft-device",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
